<a href="https://colab.research.google.com/github/JosseArturo/ColabTest/blob/master/Test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [4]:
# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [8]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    print (output)

Test String


In [14]:
 
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),tf.cast(tf.constant(1),tf.float64))
 
with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


In [0]:
##############################
#Logistic Classifier
##############################

In [0]:
#Logistic Classifier

import tensorflow as tf

def get_weights(n_features, n_labels):
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    get_weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
    # TODO: Return weights
    return get_weights


def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    get_biases = tf.Variable(tf.zeros(n_labels))
    # TODO: Return biases
    return get_biases


def linear(input, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    y=  tf.add(tf.matmul(input,w),b)
    # TODO: Linear Function (xW + b)
    
    return y
  

In [17]:
mport tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from test import *

def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []
    mnist_labels = []

    mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

    # In order to make quizzes run faster, we're only looking at 10000 images
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):

        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels


# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

# Features and Labels
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

# Training data
train_features, train_labels = mnist_features_labels(n_labels)
init = tf.global_variables_initializer()


with tf.Session() as session:
    # TODO: Initialize session variables
    session.run(init)
    # Softmax
    prediction = tf.nn.softmax(logits)

    # Cross entropy
    # This quantifies how far off the predictions were.
    # You'll learn more about this in future lessons.
    cross_entropy = -tf.reduce_sum(labels * tf.log(prediction), reduction_indices=1)

    # Training loss
    # You'll learn more about this in future lessons.
    loss = tf.reduce_mean(cross_entropy)

    # Rate at which the weights are changed
    # You'll learn more about this in future lessons.
    learning_rate = 0.08

    # Gradient Descent
    # This is the method used to train the model
    # You'll learn more about this in future lessons.
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

    # Run optimizer and get loss
    _, l = session.run(
        [optimizer, loss],
        feed_dict={features: train_features, labels: train_labels})

# Print loss
print('Loss: {}'.format(l))



Extracting /datasets/ud730/mnist/train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-labels-idx1-ubyte.gz
Loss: 15.78938102722168


In [19]:
##Grader done by Udacity

import numpy as np
import tensorflow as tf
from tensorflow.python.framework.errors import FailedPreconditionError
import os
import sys

def is_weights_good(w):
    w_answer = [[-0.01811021,  0.51838213],
 [ 0.05832403, -0.48847285],
 [-0.37598562, -0.7711397 ],
 [-0.5922465, -0.3118519 ],
 [ 0.21055079, -1.1010232 ]] 
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        w_result = sess.run(w)
      
    return np.allclose(w_answer, w_result)


def is_biases_good(b):
    b_answer = [0.0, 0.0]
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        b_result = sess.run(b)
        
    return np.array_equal(b_answer, b_result)


def is_linear_good(l, test_input):
    
    logits_answer = [[-2.34565091, -9.52450562],[-8.03849602, -9.28480148]]

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        logits_result = sess.run(l, feed_dict={test_input: [[1,2,3,4,5], [6,7,8,9,0]]})
        
    return np.allclose(logits_answer, logits_result)

def get_result(get_weights, get_biases, linear):
    result = {
        'correct': False,
        'feedback': 'That\'s the wrong answer.',
        'comment': ''}

    tf.set_random_seed(123456)
    
    n_features = 5
    n_labels = 2
    test_input = tf.placeholder(tf.float32)
    
    weights = get_weights(n_features, n_labels)
    biases = get_biases(n_labels)
    lin = linear(test_input, weights, biases)

    if not isinstance(weights, tf.Variable):
        result['feedback'] = 'Function weights not returning tf.Variable type.'
        result['comment'] = 'Use the tf.Variable function.'
    elif not isinstance(biases, tf.Variable):
        result['feedback'] = 'Function biases not returning tf.Variable type.'
        result['comment'] = 'Use the tf.Variable function.'
    elif weights.get_shape() != (n_features, n_labels):
        result['feedback'] = 'Function weights is returning the wrong shape.'
    elif biases.get_shape() != n_labels:
        result['feedback'] = 'Function biases is returning the wrong shape.'
    elif not is_weights_good(weights):
        result['feedback'] = 'Function weights isn\'t correct.'
    elif not is_biases_good(biases):
        result['feedback'] = 'Function biases isn\'t correct.'
    elif not is_linear_good(lin, test_input):
        import pdb;pdb.set_trace()
        result['feedback'] = 'Function linear isn\'t correct.'
    else:
        try:
            std_out = sys.stdout
            f = open(os.devnull, 'w')
            sys.stdout = f
        
        except FailedPreconditionError as err:
            if err.message.startswith('Attempting to use uninitialized value Variable'):
                result['feedback'] = 'At least one variable is not initialized.'
            else:
                raise err
        else:
            result['correct'] = True
            result['feedback'] = 'You got it!  That\'s the correct answer.'
        finally:
            sys.stdout = std_out
    return result

def run_grader(get_weights, get_biases, linear):
    
    try:
    # Get grade result information
        result = get_result(get_weights, get_biases, linear)
    except Exception as err:
        # Default error result
        result = {
            'correct': False,
            'feedback': 'Something went wrong with your submission:',
            'comment': str(err)}

    feedback = result.get('feedback')
    comment = result.get('comment')

    print(f"{feedback}\n{comment}\n")



if __name__ == "__main__":
    run_grader(get_weights, get_biases, linear)

Function weights isn't correct.




In [22]:

### DON'T MODIFY ANYTHING BELOW ###
### Be sure to run all cells above before running this cell ###
#import grader

try:
    run_grader(get_weights, get_biases, linear)
except Exception as err:
    print(str(err))

Function weights isn't correct.




In [0]:
##############################
#Logistic Classifier ends
##############################

In [0]:
##############################
#Softmax function
##############################

In [5]:
# Solution is available in the other "solution.py" tab
import numpy as np


def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    # TODO: Compute and return softmax(x)
    return np.exp(x)/np.sum(np.exp(x))
    
logits = [3.0, 1.0, 0.2]
print(softmax(logits))


[0.8360188  0.11314284 0.05083836]


In [0]:
##############################
#Softmax function TENSOR
##############################

[0.6590012 0.242433  0.0985659]

In [13]:
import tensorflow as tf


def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.constant(logit_data)
    #logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)
    
    with tf.Session() as sess:
        pass
        # TODO: Feed in the logit data
        output = sess.run(softmax, feed_dict={logits:logit_data})   
   
    return output
  
out = run()
print (out)

[0.6590012 0.242433  0.0985659]


In [0]:
##############################
#Mini Batch
##############################


In [0]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    outout_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        outout_batches.append(batch)
        
    return outout_batches

In [10]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np

learning_rate = 0.05
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Extracting /datasets/ud730/mnist/train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-labels-idx1-ubyte.gz


In [13]:
# TODO: Set batch size
batch_size = 32
assert batch_size is not None, 'You must set the batch size'

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for i in range(20): #Added to get more iteractions an improve gradient retropropagation
        # TODO: Train optimizer on all batches
        for batch_features, batch_labels in batches(batch_size, train_features, train_labels):
        # for batch_features, batch_labels in ______
            sess.run(optimizer, feed_dict={features: batch_features, labels: batch_labels})

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(accuracy, feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Test Accuracy: 0.8982999920845032
